CREATE TABLE IF NOT EXISTS `task` (
  task_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  date VARCHAR(32) NOT NULL COMMNET '起始日期',
  status ENUM('pending','success','failed') NOT NULL DEFAULT 'pending' COMMENT '任务状态',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_output` (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  time_index SMALLINT UNSIGNED NOT NULL COMMENT '时间点0-23',
  ts DATETIME NOT NULL COMMENT '时间戳',
  value DOUBLE NOT NULL COMMENT '数值',
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_time (task_id, time_index),
  KEY idx_task (task_id),
  CONSTRAINT fk_task_output_task FOREIGN KEY (task_id) REFERENCES task(task_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;